# prometheus/prometheus.yml

global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: kafka
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metric_relabel_configs:
    - source_labels: [instance]
      separator: ':'
      regex: 'kafka-(\d):.*'
      replacement: 'kafka-${1}:900${1}'
      target_label: instance
    static_configs:
      - targets: ["kafka-0:9200", "kafka-1:9200", "kafka-2:9200"]

  - job_name: node
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metric_relabel_configs:
    - source_labels: [instance]
      separator: ':'
      regex: 'kafka-(\d):.*'
      replacement: 'kafka-${1}:900${1}'
      target_label: instance
    static_configs:
      - targets: ["kafka-0:9100", "kafka-1:9100", "kafka-2:9100"]
